# SPDX-License-Identifier: GPL-2.0-only

obj-y += main.o
obj-y += walk.o
obj-y += protect.o
obj-y += module.o
obj-y += patch.o
obj-$(CONFIG_HEKI_KUNIT_TEST) += heki-test.o
obj-$(CONFIG_KEXEC_FILE) += kexec.o
obj-$(CONFIG_JUMP_LABEL) += patch_jump_label.o
